# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [2]:
'''
Your Code
'''
print('np.zeros產生所有元素為0的矩陣')
print('np.empty產生為初始化的元素')
print('為初始化的情況下，使用np.empty，要初始化的情況，使用np.zeros')

np.zeros產生所有元素為0的矩陣
np.empty產生為初始化的元素
為初始化的情況下，使用np.empty，要初始化的情況，使用np.zeros


### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [3]:
# 記得先 Import 正確的套件

'''
Your Code
'''
import numpy as np

In [8]:
# 參考解答

a = np.random.rand(2, 3)

'''
Your Code
'''
print('before change: ',a)
print('after change: ',a.astype(int))
print(a.round())
print(np.round(a))

before change:  [[0.09963975 0.90079978 0.98156831]
 [0.21664993 0.69576621 0.10119783]]
after change:  [[0 0 0]
 [0 0 0]]
[[0. 1. 1.]
 [0. 1. 0.]]
[[0. 1. 1.]
 [0. 1. 0.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [10]:
m = 20
n = 40

'''
Your Code
'''
np.reshape(np.linspace(20,40,6),(2,3))

array([[20., 24., 28.],
       [32., 36., 40.]])

In [15]:
a = np.random.rand(2,3)*(n-m)
b = a
print(a)
print(b)
print( (a - b%1) + m )

[[ 1.58992025 16.18270135  3.25459931]
 [ 5.25448244  0.40875187  4.91274245]]
[[ 1.58992025 16.18270135  3.25459931]
 [ 5.25448244  0.40875187  4.91274245]]
[[21. 36. 23.]
 [25. 20. 24.]]
