作業目標:<br>
在array中，可以靈活應用索引幫助資料擷取<br>
作業重點:<br>
陣列的屬性需要注意使用方式<br>
陣列之中索引是由0開始請同學注意

題目:<br>
1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。<br>
2.呈上題，將以上數列取出偶數。<br>
3.呈1題，將數列取出3的倍數。<br>

In [5]:
import numpy as np

In [19]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
a = np.arange(0,21,1)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [21]:
#2.呈上題，將以上數列取出偶數。
a_2 = a[0::2]
print(a_2)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [22]:
#3.呈1題，將數列取出3的倍數。
a_3 = a[0::3]
print(a_3)

[ 0  3  6  9 12 15 18]


In [23]:
#4.[簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？
print('List會把第一層的元素轉換成list')
print('tolist()可以把輸入的數據全部list話')

List會把第一層的元素轉換成list
tolist()可以把輸入的數據全部list話


In [25]:
# 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）
# a = np.random.randint(10, size=6) 
# b = np.random.randint(10, size=(3,4)) 
# c = np.random.randint(10, size=(2,3,2)) 

a = np.random.randint(10, size = 6)
b = np.random.randint(10, size = (3,4))
c = np.random.randint(10, size = (2,3,2))

for i in [a,b,c]:
    print(i.ndim,i.shape,i.size,i.dtype,i.itemsize,len(i),type(i),sep='\n',end='\n'*3)

1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>




In [28]:
a = np.arange(1,42,2).reshape(3,7)
print(list(a))
print(a.tolist())

[array([ 1,  3,  5,  7,  9, 11, 13]), array([15, 17, 19, 21, 23, 25, 27]), array([29, 31, 33, 35, 37, 39, 41])]
[[1, 3, 5, 7, 9, 11, 13], [15, 17, 19, 21, 23, 25, 27], [29, 31, 33, 35, 37, 39, 41]]
